SachOnline/SachOnline/Controllers/SachOnlineController.cs
using SachOnline.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {
        private SachOnlineEntities data = new SachOnlineEntities();
        // GET: SachOnline
        public ActionResult Index()
        {
            var listSachMoi = LaySachMoi(6);
            return View(listSachMoi);
        }
        
        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        private List<NHAXUATBAN> NhaXB(int count)
        {
            return data.NHAXUATBANs.OrderByDescending(a => a.MaNXB).Take(count).ToList();
        }
        // GET: SachOnline/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SachOnline/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SachOnline/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SachOnline/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SachOnline/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SachOnline/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SachOnline/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult ChuDePartialView()
        {
            var listchude = from cd in data.CHUDEs select cd;
            return PartialView(listchude);
        }
        public ActionResult NXBPartialView()
        {
            var listNXB = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(listNXB);
        }
        public ActionResult SachTheoChuDe(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SachTheoNhaXuatBan(int id)
        {
            var sachs = from nxb in data.SACHes where nxb.MaNXB == id select nxb;  
            return View(sachs);
        }
    }
}

SachOnline/SachOnline/Views/Shared/_BookPricePartialView.cshtml
<h2 class="text-center">SÁCH BÁN NHIỀU</h2>
<div class="row">
    <div class="col-lg-6 col-md-6">
        <div class="media-object-default">
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object imgsachbannhieu"
                             src="~/Style/Images/TH004.jpg" alt="placeholder image">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Tên sản phẩm 1</h4>
                    Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                </div>
            </div>
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object imgsachbannhieu"
                             src="~/Style/Images/TH005.jpg" alt="placeholder image">

                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Tên sản phẩm 1</h4>
                    Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                </div>
            </div>
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object imgsachbannhieu"
                             src="~/Style/Images/TH006.jpg" alt="placeholder image">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Tên sản phẩm 1</h4>
                    Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="media-object-default">
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object imgsachbannhieu"
                             src="~/Style/Images/TH007.jpg" alt="placeholder image">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Tên sản phẩm 1</h4>
                    Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                </div>
            </div>
        </div>
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object imgsachbannhieu"
                         src="~/Style/Images/TH008.jpg" alt="placeholder image">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">Tên sản phẩm 1</h4>
                Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
            </div>
        </div>
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object imgsachbannhieu"
                         src="~/Style/Images/TH001.jpg" alt="placeholder image">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">Tên sản phẩm 1</h4>
                Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
            </div>
        </div>
    </div>
</div>

    <!-- row-->

SachOnline/SachOnline/Views/Shared/_ContainerPartialView.cshtml
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
    <ul class="list-group">
        <li class="list-group-item active" style="font-weight:bold; text-align:center">SÁCH THEO CHỦ ĐỀ</li>
        <a href="#" class="list-group-item">Ngoại ngữ</a>
        <a href="#" class="list-group-item">Công nghệ thông tin</a>
        <a href="#" class="list-group-item">Luật</a>
        <a href="#" class="list-group-item">Văn học</a>
        <a href="#" class="list-group-item">Khoa học kỹ thuật</a>
        <a href="#" class="list-group-item">Nông nghiệp</a>
        <a href="#" class="list-group-item">Lịch sử, địa lý</a>
        <a href="#" class="list-group-item">Kinh tế</a>
        <a href="#" class="list-group-item">Nghệ thuật sống</a>
        <li class="list-group-item active" style="font-weight:bold; text-align:center">SÁCH THEO NHÀ XUẤT BẢN</li>
        <a href="#" class="list-group-item">Nhà xuất bản trẻ</a>
        <a href="#" class="list-group-item">NXB Thống kê</a>
        <a href="#" class="list-group-item">Kim Đồng</a>
        <a href="#" class="list-group-item">Văn học</a>
        <a href="#" class="list-group-item">Đại học quốc gia</a>
        <a href="#" class="list-group-item">Văn hóa nghệ thuật</a>
        <a href="#" class="list-group-item">Văn hóa</a>
        <a href="#" class="list-group-item">Lao động - xã hội</a>
        <a href="#" class="list-group-item">Khoa học & kỹ thuật</a>

    </ul>
    <br>

</div>

SachOnline/SachOnline/Views/Shared/_FooterPartialView.cshtml
<footer class="container well">
    <div style="text-align :center">
        <p>Nguyễn Kim Hoàng : 2124802010093</p>
        <p>Nguyễn Đậu Toàn : 2124802010830</p>
    </div>
</footer>

SachOnline/SachOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <style type="text/css">
        .imgbook {
            transition: all 1s ease-in;
            width: 400px;
        }

            .imgbook:hover {
                transform: scale(0.9);
                cursor: pointer;
            }

        .imgsachbannhieu {
            width: 100px;
        }
    </style>
</head>
<body>
    <!--Nav-->
    <nav class="navbar navbar-inverse">
        <!--navbar-fixed-top-->
        @Html.Partial("_NavPartialView")
        <!-- /.container-->
    </nav>
    <!--End-Nav-->

    
    <!--Phần tìm kiếm-->
    
    <!--Phần Slide-->
    <div class="container">
        @Html.Partial("_SlidePartiaView")
        
    </div>
    <!--End-Phần Slide-->
    <div class="container">
        <div class="row">

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <ul class="list-group">
                    @Html.Action("ChuDePartialView", "SachOnline")
                    @Html.Action("NXBPartialView", "SachOnline")
                </ul>
                
            </div>
            
    </div>

            @RenderBody()
            <hr>
        </div>
        <!-- /.container-->
        <!--Sách bán nhiều-->
        <div class="container">
            @Html.Partial("_BookPricePartialView")

        </div>
        <!-- /.container-->
        <!--Footer-->
        @Html.Partial("_FooterPartialView")
        <!--End-Footer-->
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link href="~/Style/css/bootstrap.css" rel="stylesheet" />
        <script src="~/Style/js/bootstrap.js"></script>
        <a href="~/Style/js/jquery-1.11.3"></a>
        <script src="~/Style/js/jquery-1.11.3.min.js"></script>
</body>
</html>

SachOnline/SachOnline/Views/Shared/_NavPartialView.cshtml
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data- target="#navbar1" aria-expanded="false">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">SachOnline</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar1">
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">TRANG CHỦ</a> </li>
            <li class="active"><a href="#">GIỚI THIỆU</a> </li>
            <li class="active"><a href="#">LIÊN HỆ</a> </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">Người dùng
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-user"></span> Đăng ký</a> 
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-log-in"></span> Đăng nhập</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                <span class="glyphicon glyphicon-shopping-cart"></span> Giỏ hàng (0)</a>
            </li>
        </ul>
        <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Tìm kiếm">
            </div>
            <button type="submit" class="btn btn-default">Tìm</button>
        </form>
    </div>
    <!--Tìm kiếm-->
</div>
<!--End-Phần tìm kiếm-->

SachOnline/SachOnline/Views/Shared/_SlidePartiaView.cshtml
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <div id="carousel1" class="carousel slide">
            <ol class="carousel-indicators">
                <li data-target="#carousel1" data-slide-to="0" class="active"> </li>
                <li data-target="#carousel1" data-slide-to="1" class=""> </li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="img-responsive" src="~/Style/Images/Slider/01.jpg" alt="thumb">

                    <div class="carousel-caption"> Quảng cáo 2 </div>
                </div>
                <div class="item">
                    <img class="img-responsive" src="~/Style/Images/Slider/02.jpg" alt="thumb">
                    <div class="carousel-caption"> Quảng cáo 2 </div>
                </div>

            </div>
            <a class="left carousel-control" href="#carousel1" data-slide="prev"><span class="icon- prev"></span></a> <a class="right carousel-control" href="#carousel1" data-slide="next"><span class="icon-next"></span></a>
        </div>
    </div>
</div>